# M14: разрез в 2D на КОСОЙ границе — отчёт (2026-07-26)

Инструменты: `src/cut2d.{c,h}` (точное интегрирование по многоугольнику),
`tests/test_cut2d.c` (19/19), стенд `tools/carrier_cut2d.c`. ccheck CLEAN,
набор 1128/1128. Аудит, фальсификаторы и предсказанные провалы записаны ДО
кода: `result/M14_AUDIT.md`.

## ВЕРДИКТ ОДНОЙ СТРОКОЙ
**Разрез переносится из 1D в 2D полностью и при любом угле: 0.229 без разреза
против 1.3e-7 с разрезом — отношение 1.8·10⁶, и 1.3e-7 есть измеренный ПОЛ
МЕТРИКИ, а не ошибка.** Пол неразрезанного элемента подтверждён в 2D (0.229
против 0.206 в 1D, чуть ХУЖЕ, как и должно быть при большем носителе) и не
убывает с шириной на ШЕСТИ порядках, вплоть до 10⁵λ. Условие 1 врезки A4
закрыто: интегрирование косого разреза существует в замкнутой форме, стоит
O(рёбер) и не зависит от ω.

**И побочно — главное проектное число сессии: закон ошибки от СМЕЩЁННОГО
разреза измерен, и он в 27 раз мягче, чем предполагала врезка A4.**

## [1] ЧЕТЫРЕ ВЕТВИ (граница под 30°, падение под 30°, контраст n = 1.5)

| W/λ | 1a без разреза | 1b без разреза, ВСЕ направления | 2 РАЗРЕЗ | 4 разрез + глобальная несущая |
|---|---|---|---|---|
| 0.125 | 1.32e-3 | 8.17e-4 | 8.2e-8 | 1.09e-4 |
| 1 | 7.98e-2 | 7.04e-2 | 9.6e-8 | 0.124 |
| 10 | 0.2261 | 0.2186 | 1.27e-7 | 0.594 |
| 100 | 0.2293 | 0.2222 | 1.26e-7 | 0.594 |
| 10³ | 0.2294 | 0.2222 | 9.8e-8 | 0.594 |
| 10⁴ | 0.2294 | 0.2222 | 9.8e-8 | 0.594 |
| 10⁵ | 0.2294 | 0.2222 | 0 | 0.594 |

dim 337 / 480 / 480 / 480, ранг 172 / 258 / 211 / 211.

**По углам (W = 10λ):** без разреза 0.206 / 0.239 / 0.226 / 0.244 при
α = 0/15/30/45°, с разрезом 0 / 1.3e-8 / 1.3e-7 / 0. **Ни пол, ни его снятие от
угла не зависят** — то есть дело не в удачной ориентации.

## [2] ГЛАВНОЕ УТОЧНЕНИЕ: пол — это ИЗЛОМ, а не волновое число
Ветвь 1b даёт накрывающему границу элементу ВСЕ ТРИ истинных направления
(падающее, отражённое, прошедшее) — «бедняцкий разрез», обогащение без
разрывности. Выигрыш: 0.2294 → 0.2222, то есть **3%**.

Значит из 23% пола на неверную несущую приходится 0.7 пункта, а остальные 22 —
на то, что одна ГЛАДКАЯ огибающая обязана изобразить излом. Добавлять
направления бесполезно; помогает только разрывность. Это ровно то различие,
ради которого в плане написано «разрез, а не измельчение и не обогащение», и
теперь оно измерено, а не выведено. **Предсказание аудита (1b в полосе
0.05–0.20) НЕ ОПРАВДАЛОСЬ — измеренное 0.222 вне полосы, в худшую сторону.**
Записано как ошибка предсказания; вывод от этого только жёстче.

## [3] ЗАКОН СМЕЩЁННОГО РАЗРЕЗА (F3) — и он НЕ ИЗ ТРЁХ КАНДИДАТОВ АУДИТА

| W/λ | kδ=0.01 | 0.03 | 0.1 | 0.3 |
|---|---|---|---|---|
| 1 | 5.0e-7 | 7.5e-6 | 1.39e-4 | 1.65e-3 |
| 10 | 1.9e-7 | 2.5e-6 | 4.97e-5 | 7.50e-4 |
| 100 | 1.2e-7 | 7.9e-7 | 1.59e-5 | 2.45e-4 |
| 10³ | 9.5e-8 | 2.6e-7 | 5.03e-6 | 7.78e-5 |

Подгонка `err = C·(kδ)^p·(kW)^q` по точкам выше пола метрики:
`p = 2.471 / 2.492 / 2.494` при W = 10/100/10³ λ; `q = −0.485 / −0.499`.
```
err = 0.125 · (kδ)^2.5 · (kW)^(−1/2)   ==   0.125 · (kδ)² · sqrt(δ/W)
```
Константа `C` = 0.1206…0.1261 на шести точках (разброс 4%), закон держится в
пределах 4% на двух порядках по W и полутора по δ. При W = λ он ломается (50%
отклонения) — асимптотика начинается с W ≳ 10λ.

**Три кандидата аудита были (p,q) = (1,0) фазовый, (2,0) рэлеевский,
(1.5,−0.5) F5-подобный. Ни один не верен.** Измеренный закон читается как
произведение двух множителей, каждый со смыслом: `(kδ)²` — фазовая ошибка
входит КВАДРАТИЧНО (первый порядок сокращается сам, даже при РАВНОМЕРНОМ
смещении, потому что коэффициенты пересогласуются), а `sqrt(δ/W)` — L2-разбавление
дефекта, сидящего в полоске относительной ширины δ/W.

### Что это даёт как проектное правило
Фасетированная граница (линейная интерполяция в узле среды, врезка A4) с `m`
фасетами на элемент даёт стрелку дуги `δ = (W/m)²/(8ρ)`. Подстановка:
```
размер фасета  h = W/m = sqrt(8ρ/k) · [ε·sqrt(kW)/C]^(1/5)
```
`h ∝ W^{1/5}` — то есть **размер фасета почти не зависит от размера элемента**:
он задаётся ПОВЕРХНОСТЬЮ (`sqrt(ρλ)`) и целевой точностью. Числа при λ=550 нм,
ρ=0.5 м, цель 1%:

| элемент W | 1 мм | 1 см | 10 см | 1 м |
|---|---|---|---|---|
| фасет h | 0.91 мм | 1.14 мм | 1.44 мм | 1.81 мм |
| фасетов на элемент m | 1.1 | 8.7 | 69 | 552 |

Наивный линейный (фазовый) закон `kδ ≤ ε` потребовал бы h = 0.042 мм, то есть
**в 27 раз мельче по стороне и в 747 раз больше фасетов в 3D**. Врезка A4
считала по нему — она была пессимистична почти на три порядка.
Фасетов на 10 м² кривизны в комнате: **7.6e6 против 2e8 элементов, то есть 4%
бюджета.** Плоская стена по-прежнему стоит НОЛЬ фасетов.

**ТРЕТИЙ РЕГУЛЯТОР ТЕПЕРЬ С ЧИСЛОМ: размер элемента задаёт камера (LOD),
размер фасета задаёт поверхность, и они связаны только слабой степенью W^{1/5}.**

## [4] ФАЛЬСИФИКАТОРЫ
- **F1 (пол F5 переносится в 2D) — ПРОЙДЕН.** 0.2294 при пороге 0.10–0.35, и
  чуть ХУЖЕ одномерных 0.206, как и требовал довод «носитель больше, порче есть
  куда размазываться». Легче не стало — значит это не артефакт размерности.
- **F2 (разрез переносится) — ПРОЙДЕН ПО СУЩЕСТВУ, порог был поставлен неверно.**
  Требовалось ≤1e-10; измерено 1e-7. Но NC2 (нулевой контраст, где истинная
  ошибка ТОЖДЕСТВЕННО ноль) даёт 9.4e-8 — то есть **1e-7 есть пол самой
  метрики**: `e² = ‖u‖² − 2Re⟨u,v⟩ + ‖v‖²` считается как разность величин
  порядка единицы, поэтому `e` не может быть ниже ~sqrt(eps·cond). Порог 1e-10
  был недостижим для МЕТРИКИ, а не для метода; в 1D тот же пол виден как 3.0e-8
  в колонке M9b §7. Ошибка аудита, записана как ошибка.
- **F3 (закон смещения) — ЗАКОН НАЙДЕН, НО НЕ ИЗ МОЕГО СПИСКА.** См. [3].
- **F4 (интегратор) — ПРОЙДЕН.** 19/19 в `tests/test_cut2d.c`: против
  сепарабельной замкнутой формы `src/phi.c` (1e-16 от натурального масштаба),
  против независимого свидетеля на КОСОЙ геометрии (6e-16), аддитивность
  половин (2e-16), инвариантность транспонирования (ровно 0).
- **F5 (RCOND) — ПРОЙДЕН для вердикта.** Без разреза 0.22605 на всех четырёх
  порогах 1e-14…1e-8 (не меняется вовсе). С разрезом 0 / 1.3e-7 / 1.6e-7 /
  1.2e-5 — число у пола, как и положено, ползёт; но разделение шести порядков
  между ветвями от RCOND не зависит.

## [5] НЕГАТИВНЫЕ КОНТРОЛИ
- **NC1 (нарушенный Снеллиус в БАЗИСЕ) — ПРОЙДЕН ПОСЛЕ ПОЧИНКИ СТЕНДА: 0.594**
  при предсказании 0.1…1. Первая версия — см. артефакт 16 ниже.
- **NC2 (нулевой контраст) — ПРОЙДЕН: 0 / 2.7e-8 / 9.4e-8** при предсказании
  ≤1e-12. Формально порог не взят, и это ровно то же измерение пола метрики,
  что в F2; контроль сделал больше, чем от него ждали, — он этот пол ИЗМЕРИЛ.
- **NC3 (α=0, θ=0 против опубликованной 1D-колонки) — ПРОЙДЕН НА ПОЛКЕ, РАСХОДИТСЯ
  НА МАЛЫХ W, и расхождение объяснимо.** 0.2050 / 0.2087 против M9b 0.203 /
  0.206 при W = 10λ / 100λ — совпадение 1.5%. При W = λ/8 и λ: 7.5e-4 и 6.4e-2
  против 3.4e-3 и 4.0e-2. Причина не в размерности: **поле другое**. У M9b F5
  амплитуда по обе стороны равна 1 (чистый излом), здесь — физическое поле
  Френеля с R и T. На полке обе постановки сходятся к одному «одна огибающая не
  держит две волны», на малых W ошибка зависит от того, КАКОЙ излом.
- **NC4 (мерить в окне ПОДГОНКИ) — ПРОЙДЕН, направление предсказано верно.**
  0.1615 против 0.2261 — окно подгонки занижает ошибку на 29%, потому что оно
  вчетверо больше по площади и разбавляет приграничную ошибку свободным полем.
  Правило ±4W/±2W из M9b оправдано: без него в отчёт ушло бы 0.16.

## [6] ПОЙМАННЫЙ АРТЕФАКТ (ШЕСТНАДЦАТЫЙ ЗА ПРОЕКТ)
**16. Негативный контроль, сломанный СОГЛАСОВАННО.** Первая версия NC1
поворачивала направление прошедшей волны на 10° и в БАЗИСЕ, и в ПОЛЕ. Поле и
базис остались согласованы, поле осталось точно представимым, и контроль вернул
**1.16e-7 — ровно то же, что правильный разрез**. В таком виде он был бы
прочитан как «разрез работает», хотя не проверял ничего.
Признак, по которому пойман: **негативному контролю нечего делать на полу
метрики**. Если «сломанная» конфигурация садится туда же, куда исправная, —
сломано не то, что задумано.
Мораль общая и она новая для каталога: ломать надо ОДНУ сторону сравнения.
Контроль, который ломает и утверждение, и его проверку, самосогласован и пуст.

Отдельно, и это не артефакт метода, а два дефекта ОБУСЛОВЛЕННОСТИ интегратора,
пойманные юнит-тестами ДО всякой физики (ради чего тесты и писались первыми):
1. рекурсия антипроизводной делит на `iω` и теряет `deg!/(ωw)^deg` — 7.6e-10
   на строке ω=0 при пороге поглощения 1e-2. Лечение — поглощать экспоненту в
   полином ПОПИЕЦЕВО при `|ω|w < 1`;
2. композиция полинома степени 27 из координаты, начало которой в нескольких
   единицах, — рост `offset^27` и обратное сокращение, 1.1e-13 в строках
   аддитивности. Лечение — композиция в локальный параметр подребра.
Оба видны только на СВЕРКЕ С НЕЗАВИСИМОЙ ФОРМОЙ; ни один не поднял бы флага в
физическом прогоне — он бы просто дал «ошибку метода» 1e-10.

## [6b] КОНФОРМНОСТЬ В 2D — ИЗМЕРЕНА, И ПРЕДСКАЗАНИЕ ВЕРНО ЛИШЬ НАПОЛОВИНУ
Приём M9b §8, поднятый в 2D: к полю добавлена «призрачная» плоская волна,
направления которой в базисе НЕТ, — по обе стороны сразу, чтобы само поле
осталось непрерывным (добавь её с одной стороны, и разрыв будет у поля, а
измерение потеряет смысл). Тогда обе стороны представимы лишь приближённо, и
двум независимым односторонним проекциям не с чего совпадать на разрезе.
Скачок берётся максимумом по линии разреза внутри окна измерения.

| W/λ | призрак | ошибка | скачок/\|u\| | скачок/ошибка |
|---|---|---|---|---|
| 1 | 0 | 9.6e-8 | 1.1e-7 | 1.18 |
| 10 | 0 | 1.3e-7 | 8.8e-8 | 0.69 |
| 100 | 0 | 1.3e-7 | 7.4e-8 | 0.59 |
| 1 | 0.10 | 0.0932 | **0.302** | **3.24** |
| 10 | 0.10 | 0.1099 | 2.3e-3 | 0.021 |
| 100 | 0.10 | 0.1099 | 6.7e-7 | 6.1e-6 |
| 1 | 0.30 | 0.2645 | **1.065** | **4.03** |
| 10 | 0.30 | 0.3149 | 8.9e-3 | 0.028 |
| 100 | 0.30 | 0.3149 | 2.4e-6 | 7.7e-6 |

Строки с нулевым призраком — обе величины на полу метрики, то есть говорят
ровно НИЧЕГО: это та самая дыра, которую §7 нашёл у себя. Ради них измерение и
делалось с призраком.

**ЧТО ПОЛУЧИЛОСЬ.**
1. Скачок ЛИНЕЕН по амплитуде призрака (0.302→1.065 и 2.3e-3→8.9e-3 при росте
   призрака втрое) — то есть это свойство непредставимой части, а не дефект.
2. **Скачок падает с шириной элемента КРУТО и быстрее любой степени**: при
   призраке 0.1 — 0.302 / 2.3e-3 / 6.7e-7 на W = 1/10/100λ, то есть в 130 и
   затем в 3500 раз за декаду. Ошибка приближения при этом стоит на 0.11.
3. **ПРЕДСКАЗАНИЕ («скачок на 2–3 порядка ниже ошибки, как в 1D») ВЕРНО ТОЛЬКО
   ПРИ W ≥ 10λ** (отношения 0.021 и 6e-6). **При W = λ оно ПРОВАЛИЛОСЬ: скачок
   в 3–4 раза БОЛЬШЕ ошибки**, а при призраке 0.3 достигает 1.07 амплитуды поля.

**Читается так: неконформность разреза — явление МЕЛКИХ элементов.** У крупного
элемента базис на каждой стороне жёсткий (одна несущая, мало функций), обе
стороны делают почти одинаковую гладкую ошибку, и в разности она сокращается;
у мелкого каждая сторона свободна извиваться по-своему. Для архитектуры,
которая живёт при W ≫ λ, направление удачное. Но это прямое предупреждение для
УТОЧНЕНИЯ У ПОВЕРХНОСТИ (регулятор 2): там элементы мелкие, и неконформность
разреза может стать главной ошибкой именно в том месте, куда её приходят чинить.
ОГОВОРКА, без которой вывод был бы завышен: L2-проекция скачок не штрафует
вообще, поэтому это ВЕРХНЯЯ оценка того, что сделает сам метод, и НИЖНЯЯ оценка
того, во что он обойдётся в галёркинской постановке, где скачок входит через
производные (M9b §8).

## [7] ЧЕГО ЭТОТ СТЕНД НЕ ГОВОРИТ
- **Проекция, не Галёркин.** Ни оператора, ни границы домена, ни решателя.
  Нижняя граница: провал был бы приговором, успех ничего не обещает про решение.
- **Конформность в 2D ИЗМЕРЕНА — см. §6b.** Скачок линеен по непредставимой
  части и падает с шириной элемента быстрее любой степени; предсказание верно
  при W >= 10 lambda и провалилось при W = lambda (скачок втрое БОЛЬШЕ ошибки).
  Что это значит для галёркинской постановки — по-прежнему открыто: L2 скачок
  не штрафует вовсе.
- **Направления ОРАКУЛЬНЫЕ** (три истинные плоские волны). Про ВЫБОР
  направлений — ничего (это M9c).
- **Граница ПРЯМАЯ.** Знакопеременное смещение (настоящая стрелка дуги внутри
  элемента) не мерилось: измерено РАВНОМЕРНОЕ смещение, худший случай без
  сокращений. Проектное правило [3] на этом и построено, то есть оно
  консервативно.
- **Один уровень**, лестницы нет ⇒ межуровневая вырожденность не участвует.
- **2D, не 3D.** В 3D та же теорема о дивергенции применяется дважды
  (многогранник → грани → рёбра); код не написан, стоимость не мерена.
- Контраст один (n = 1.5). Зависимость пола от контраста бралась из линейной
  модели M9b+M11 и здесь не проверялась.

## [8] ЧТО ЭТО МЕНЯЕТ В ПЛАНЕ
1. **Врезка A4, условие 1 — ЗАКРЫТО.** Плоский косой разрез в 2D переносится
   (1.8e6 отношение), интегрируется в замкнутой форме, стоит O(рёбер) и не
   зависит от ω. Кубатура по тетраэдрам для этого класса подынтегральных не
   нужна — этап 2 плана упрощается.
2. **Врезка A4, условие 2 — СМЯГЧЕНО НА ТРИ ПОРЯДКА и получило формулу.**
   Потолок кривизны сидит на ФАСЕТЕ, а не на элементе, и фасет крупнее, чем
   считалось: 1.1 мм вместо 0.042 мм при ρ=0.5 м и цели 1%. «LOD по базису
   бесплатен» возвращается из условного в измеренное — с оговоркой, что
   измерено на ПРЯМОЙ границе и в проекции.
3. **Остаётся открытым**: поведение в галёркинской постановке, 3D и
   знакопеременное смещение (там ожидается ещё мягче). Конформность измерена
   (§6b) и дала СОБСТВЕННОЕ ограничение: неконформность разреза — явление
   МЕЛКИХ элементов, то есть она бьёт именно по регулятору 2 (уточнение у
   поверхности), а не по крупным элементам LOD.
4. Для среза (`SLICE_PLAN.md`): маршрут B (резкий цилиндр) теперь имеет всю
   машинерию, кроме КРИВОГО разреза — а по [3] кривой разрез и не нужен,
   достаточно фасетов с измеренным правилом. Это меняет оценку маршрута B с
   «+6–8 ч новой геометрии» на «+2–3 ч фасетирования известной».
