# M15: НИТШЕ ВМЕСТО КОЛЛОКАЦИИ НА РАЗРЕЗЕ — отчёт (2026-07-26)

Код: `src/nitsche2d.{c,h}` (точные интерфейсные интегралы), `tests/test_nitsche2d.c`
(44/44), два добавления в `src/cut2d.{c,h}`, врезка в `tools/slice2d.c`.
Аудит, фальсификаторы и предсказанные провалы записаны ДО кода:
`result/M15_NITSCHE_AUDIT.md`. ccheck CLEAN, набор **1206/1206** (было 1162).

## ВЕРДИКТ ОДНОЙ СТРОКОЙ
**Ручка снята, и это измерено с обеих сторон: у коллокации по числу точек
разброс 17× с ямой (0.707 → 0.042 → 0.060), у Нитше по штрафу разброс 1.7× на
ЧЕТЫРЁХ порядках β с плато 4% на множителе 4 вокруг ПРЕДСКАЗАННОГО значения.**
И главное — **критерий A5 выполнен впервые: поле ядра упало с 0.376 до 0.0053,
в 71 раз.**

## [0] ЧИСЛА, КОТОРЫЕ ОТВЕЧАЮТ НА ЧЕТЫРЕ ВОПРОСА КОМАНДЫ

| вопрос | ответ |
|---|---|
| чему равен штраф ПО ОЦЕНКЕ | `β = γ(k_max + 2√15/W)`, при γ=1 и конфигурации гейта **24.9 λ⁻¹** — вычислено до прогона, из обратного неравенства для квадратичного куска |
| удвоение / уполовинивание | удвоение **−1.7%** (плато), уполовинивание **+52%** (граница активна) |
| вакуум воспроизводится | да: разрез принудительно включён, ошибка **0.0053** против 0.0041 у неразрезанного базиса в том же бинаре — разрез стал БЕСПЛАТНЫМ |
| портит ли D1 | нет: `|Ac|` на известной плоской волне **1.0e-11**, было 1.2e-6 БЕЗ Нитше (стало лучше, а не хуже) |

## [1] ФОРМА: ЧТО ИМЕННО ДОБАВЛЕНО (вывод, не цитата)

Носители компактны, φ ∈ C¹, поэтому теорема Грина по двум областям ТОЧНА:
```
Strong_ij ≡ ∫B_i(Δ+k²)B_j = −a_broken(B_i,B_j) − ∮_Γ([B_i]{∂ₙB_j} + {B_i}[∂ₙB_j])
```
**Сильная форма уже содержит слабую**, проинтегрированную по частям
аналитически; не хватает ровно двух поверхностных членов. Отсюда — и это главный
вывод по ОБЪЁМУ РАБОТ — Нитше стоил ОДИН новый интегральный примитив (линейный
интеграл вдоль фасета), а не пересборку оператора:
```
A_ij = Strong_ij + β_i α_j (T1_j − T1_i) − β_pen α_i α_j T0
T0 = ∮_Γ B_iB_j,  T1_j = ∮_Γ B_i ∂ₙB_j,  T1_i = ∮_Γ B_j ∂ₙB_i
[v] = α·v|_Γ, {v} = β·v|_Γ;  разрезанная: (α,β) = (σ, ½);  целая: (0, 1)
```
Собранная матрица есть МИНУС симметричная форма Нитше. Побочно: **пары
«внутренняя × внешняя» до сих пор давали РОВНО НОЛЬ** (области не пересекаются) —
связи между сторонами разреза в матрице не существовало вовсе.

Интегралы точны: интегрируемое — (кусочный полином степени ≤8 по длине
дуги)×(плоская волна), разбиение по всем узлам четырёх φ-множителей, моменты —
общий примитив с `cut2d` (не копия: копии расходятся, урок M14).

## [2] ДВЕ ПОЙМАННЫЕ ОШИБКИ, И ОБЕ ПОЙМАНЫ ПРЕДЗАРЕГИСТРИРОВАННЫМИ ПРОВЕРКАМИ

### 17. Параметр, который молча не читался (подпись знакома до буквы)
`it=` (число итераций LSQR) читался из ПОЗИЦИОННОГО аргумента, оставшегося от
прежней сигнатуры. Свип по нему дал **побитово одинаковый ответ на 1000 и 12000
итерациях**, включая `|c|` и невязку. Это ровно третья за проект реализация одной
подписи: *число не меняется при изменении параметра, которым его меняют*.
Первые две (вес DtN, число 4.768e-04 в ОДУ Ми) означали систематику; эта означала
мёртвый аргумент. **Лечение, а не заплатка: все 13 позиционных аргументов
переведены в `ключ=значение`, а НЕИЗВЕСТНЫЙ ключ — это ABORT, а не умолчание.**
Цена ошибки была бы велика: свипы по γ сравнивались бы при разной сходимости.

### 18. Знак, который симметрия НЕ МОЖЕТ поймать (ошибка аудита, не стенда)
В §1 аудита согласующая пара выписана со знаком «минус» (как в учебной записи
для другой ориентации скачка). С ним первый же физический прогон дал **хуже, чем
без Нитше вовсе: 0.62/0.73/0.64 против 0.185/0.220/0.376**, и это читалось бы как
«метод не работает».
Диагноз занял один прогон, потому что обе проверки были записаны заранее:
- **F-N3 (симметрия) ПРОШЁЛ и с неверным знаком (7.8e-16)** — и не мог не пройти:
  переворот знака у СИММЕТРИЧНОЙ пары оставляет матрицу симметричной;
- **F-N4 (согласованность на известной плоской волне) ПРОВАЛИЛСЯ: `|Ac| = 0.40`.**

Причина содержательна: недостаточно, чтобы каждый добавленный член содержал
скачок. У точного решения `[u] = [∂ₙu] = 0`, но **тестовая функция всё равно
рвётся**, и Грин оставляет `a_broken(u,v) = −∮[v]{∂ₙu}`. Интерфейсная пара обязана
это СОКРАТИТЬ, а не удвоить. После смены знака `|Ac| = 1.0e-11`.
**Мораль для каталога, новая: проверка на симметрию слепа к знаку симметричной
пары. Ловит только согласованность — и только на ЯВНО ВЫПИСАННОМ точном решении.**

## [3] ФАЛЬСИФИКАТОРЫ

| # | что | предсказание | измерено | итог |
|---|---|---|---|---|
| F-N7 | Γ интегрирования = Γ разреза | ≤1e-15 | 1.6e-15 на вершинах, 4.4e-16 на серединах рёбер, нормали наружу на всех рёбрах | ПРОЙДЕН |
| F-N6 | примитив против независимого свидетеля | ≤1e-12 | 1.6e-17…1.0e-15 (квадратура, kW ≤ 4); аддитивность 6.5e-18…3.5e-17 до kW = 200 | ПРОЙДЕН |
| F-N5* | тождество Грина против `cut2d` | ≤1e-12 | 0…1.1e-16 на 18 комбинациях (сторона × сдвиг × kW) | ПРОЙДЕН |
| F-N3 | симметрия операторного блока | ≤1e-10 после, O(1) до | **8.0e-16** после, **1.066** до | ПРОЙДЕН |
| F-N4 | согласованность на плоской волне | ≤1e-4 | **1.0e-11** (без Нитше 1.2e-6) | ПРОЙДЕН |
| F-N1 | ВАКУУМ С ПРИНУДИТЕЛЬНЫМ РАЗРЕЗОМ | 0.007–0.020 | **0.0131 / 0.0122 / 0.0053** при ND=2/4/8 | ПРОЙДЕН |
| F-N2 | вакуум без разреза не задет | те же числа | уровень и тренд те же (0.0173/0.0138/0.0041), **до знака не воспроизводится** — см. ниже | ЧАСТИЧНО |
| F-N5 | ядро в нулевом поле | ≤0.03 | **0.0053 / 0.0042 / 0.0039** (было 0.376/0.322/0.286) | ПРОЙДЕН |
| F-IV | сдвиг DtN R → 1.5R | поле меняется <2% | ошибка 1.31% → 0.79% на r=2λ, то есть поле сдвинулось меньше чем на 2% | ПРОЙДЕН |

(*) F-N5 в таблице встречается дважды: в юнит-тестах это тождество Грина (N5),
в стенде — критерий A5. Имена совпали по недосмотру нумерации, величины разные.

**Про F-N2 честно.** Побитового воспроизведения прошлых чисел добиться не
удалось: прежняя команда запускалась с позиционными аргументами, и её итерационный
предел и набор строк в записи не сохранились (а `it=` тогда, как выяснилось, вообще
не читался). Поэтому базой сравнения в этом отчёте служат числа, **переснятые тем же
бинарём в той же конфигурации**, а не числа прошлой сессии. Это сильнее, а не
слабее: сравнение «с разрезом / без разреза» матчировано по всему остальному.

## [4] ГЛАВНОЕ: ЯМА ПРОТИВ ПЛАТО, СНЯТО ОДНИМ БИНАРЁМ

Цилиндр n=1.5, W=λ/2, ND=8, R=3.5λ, 32 фасета, окно r=1.5a НЕПОДВИЖНО.

**Коллокация (число точек — ручка):**

| точек | 0 | 16 | 32 | 64 |
|---|---|---|---|---|
| ошибка | 0.707 | 0.513 | **0.0418** | 0.0601 |

Разброс **17×**, минимум внутри, дальше рост — яма подтверждена в том же коде.

**Нитше (штраф — оценка), it = 40 000:**

| γ | 0 | 0.5 | **1 (оценка)** | 2 | 4 | 8 | 32 |
|---|---|---|---|---|---|---|---|
| β, λ⁻¹ | 0 | 12.4 | **24.9** | 49.8 | 99.6 | 199 | 797 |
| r=1.5a | 0.0324 | 0.0349 | **0.0230** | 0.0226 | 0.0236 | 0.0276 | 0.0377 |
| r=2.0a | 0.0270 | 0.0288 | **0.0174** | 0.0138 | 0.0145 | 0.0166 | 0.0203 |

- **Плато γ ∈ [1,4] (множитель 4): разброс 4%.** Критерий приёмки ≤10% — взят.
- **Удвоение γ=1→2: −1.7%.** Взято.
- **Уполовинивание γ=1→0.5: +52%.** НЕ взято — и это ВТОРОЙ, заранее
  записанный допустимый исход: оценка есть граница СНИЗУ, её активность
  подтверждает вывод. Условие ветки («колено сходится с предсказанными 24.9 в
  пределах ×3») выполнено: колено лежит между β=12.4 и β=24.9.
- **Разброс по ВСЕМУ диапазону, включая γ=0 (штрафа нет вовсе): 1.67×**, и ответ
  нигде не выходит из полосы 2.3–3.8%. У коллокации выключение ручки давало
  0.707. **Это и есть содержательная разница: у Нитше работу делают согласующие
  члены, а штраф её лишь модулирует.**
- Плато **шевелится в 3-м знаке** (0.0230/0.0226/0.0236), то есть это плато, а не
  подпись «член не доходит до матрицы» (заранее записанный признак подделки).

## [5] НЕГАТИВНЫЕ КОНТРОЛИ (провал предсказан — провал получен)

| контроль | предсказание | измерено |
|---|---|---|
| NC-N1 перевёрнутый знак скачка | ≥0.3 | **0.331** |
| NC-N2 только штраф, без согласующих членов | ≥2× хуже полного, лучше отсутствия | **0.536** (полное 0.023, без члена 0.707) |
| NC-N3 коллокация в том же бинаре | яма | яма, 17× |

NC-N2 отвечает на вопрос «что несут согласующие члены»: без них `[∂ₙu]` не
ограничен НИЧЕМ (сильная форма его не видит), и ответ хуже полного Нитше в 23 раза.

## [6] КРИТЕРИЙ A5 — АРХИТЕКТУРНЫЙ РЕЗУЛЬТАТ ШАГА

Вакуум с принудительным разрезом, `d = c_LSQR − c_точное` — направление ядра
(оба вектора удовлетворяют системе, `|Ad|/(|A||d|) ≈ 6–8e-7`):

| | без Нитше | с Нитше |
|---|---|---|
| поле от `d`, r/a=1.5 / 2.0 / 2.5 | 0.376 / 0.322 / 0.286 | **0.0053 / 0.0042 / 0.0039** |
| `|d|` | 0.904 | 0.768 |

**Ядро вернулось в нулевое поле.** При этом `|d|` почти не изменилась — то есть
ядро БАЗИСА осталось таким же большим, как и задумано, а поле от него исчезло.
Это ровно то утверждение, на котором стоит «намеренно переполненный базис +
min-norm», и в 2D оно было НАРУШЕНО (PLAN, врезка A5). Теперь выполнено.

## [7] ЦИЛИНДР: ЧИСЛО ЕСТЬ, ГЕЙТ D2 НЕ ОБЪЯВЛЯЕТСЯ ВЗЯТЫМ

Ошибка поля на резком цилиндре n=1.5 (ka=6.28), W=λ/2, ND=8:

| конфигурация | r=1.5a | r=2.0a (= r_m гейта) |
|---|---|---|
| R=3.5λ, 32 фасета, γ=2 | 0.0226 | **0.0138** |
| R=5.25λ, 32 фасета, γ=1 (F-IV) | 0.0152 | **0.0079** |
| R=3.5λ, **ND=16**, γ=1 (F-II) | 0.0108 | **0.0084** |
| **NC-D (рассеивателя нет)** | **0.698** | **0.564** |

Удвоение направлений 8 → 16 УПОЛОВИНИВАЕТ ошибку (0.0211 → 0.0108), то есть
насыщения при ND=8 нет — как и предсказывает закон `ND ≈ 3+20·W/λ = 13`, по
которому ND=8 недостаточен. Насыщение F-II этим прогоном НЕ проверено (нужен
ND=32); проверено лишь, что мы левее насыщения, и это согласуется.

**ПРЕДСКАЗАНИЕ АУДИТА (8–20%) НЕ ОПРАВДАЛОСЬ — в лучшую сторону, в 6–10 раз.**
Записано как ошибка предсказания. Причина, вероятно, та же, что делала прежние
числа плохими: не разрешение, а неопределённость постановки, и она снята.

Безусловное правило плана («артефакт обязан выигрывать у своего негативного
контроля втрое») выполнено с запасом: **41× и 71×** против NC-D.

**Почему D2 всё равно не объявляется взятым, хотя 5% пройдены:**
1. измерена ОДНА из двух половин гейта — диаграмма рассеяния не мерилась;
2. ND=8 при W=λ/2 вдвое ниже закона `3+20·W/λ = 13`, то есть конфигурация не та,
   которую гейт описывает, и F-II не проверен;
3. сходимость по фасетам НЕ вышла на порядок 2: 0.0461 / 0.0211 / 0.0160 при
   16/32/64 фасетах (отношения 2.2 и 1.3) — при 32 фасетах геометрия ещё
   участвует в ошибке, а при 64 упирается в другой источник ~1.5%;
4. LSQR не на плато: 12 000 → 40 000 итераций всё ещё двигают ответ, и увеличение
   домена R=3.5λ → 5.25λ улучшает результат почти вдвое. Ошибка ограничена
   постановкой и решателем, а не дискретизацией — то есть **это верхняя оценка**;
5. конфигурация (R=3.5λ) не равна прописанной в гейте (R=5λ).

Иными словами: **порог 5% пройден, а гейт — это не только порог.**

## [8] ЧЕГО ЭТОТ ШАГ НЕ ПОКАЗЫВАЕТ

- **Крупные элементы.** Отношение «член Нитше / объёмный член» ~ `γ/(kW)`: при
  `W ≫ λ` штраф относительно слабеет. Мерилось при `W = λ/2` — самом
  благоприятном для Нитше режиме. Это записано было ДО прогона и остаётся
  открытым.
- **Тонкие дольки (slivers).** Минимальная норма строки до уравновешивания
  8.4e-7 при максимальной 986 (отношение 8.5e-10) — тревожный порог 1e-10 не
  перейдён, но запас всего в 8 раз. Ghost penalty не понадобился; при более
  мелком W понадобится.
- **Кривой разрез.** Γ фасетирован, как и раньше.
- **3D.** Там `∮` становится интегралом по многоугольной ГРАНИ: та же теорема,
  другой код, стоимость не мерена.
- **Стоимость.** dim 3568 при домене 3.5λ — утверждение о дешевизне срез
  по-прежнему не делает (§11 SLICE_PLAN в силе).

## [9] ЧТО ЭТО МЕНЯЕТ В ПЛАНЕ

1. **Врезка A5: критерий «ядро в нулевом поле» из ПРОВАЛЕННОГО становится
   ВЫПОЛНЕННЫМ**, и названа причина, по которой он был нарушен: не веер
   направлений и не усечение строк, а невидимый оператору скачок на разрезе.
2. **Разрез без члена Нитше — не «менее точная», а НЕ ОПРЕДЕЛЁННАЯ конструкция.**
   Теперь это измерено с обеих сторон (0.376 против 0.0053 в вакууме) и должно
   быть записано как требование, а не как опция: cut ⇒ Nitsche, всегда.
3. **Открытый вопрос 13 плана («что решает систему») сузился**: система больше
   не недоопределена по полю; узкое место — СКОРОСТЬ LSQR (40 000 итераций всё
   ещё двигают ответ), то есть тот же критический путь, что назвал M11.
4. Для среза: следующий шаг — не разрез, а ND (закон F-II) и плато LSQR;
   гейт D2 достижим и, судя по R=5.25λ, с запасом.
