# M19: ЗНАМЕНАТЕЛЬ И ИЗБЫТОЧНОСТЬ — отчёт (2026-07-26)

План/аудит/исправление — в переписке; исполнение по нему. Две страницы, вывод
первым абзацем.

## ВЫВОД
**Знаменатель снять НЕ УДАЛОСЬ, и причина — не в обычном базисе, а в стенде.**
Least-squares постановка с ~dim ОДНОРОДНЫМИ строками оператора против 91 строки
DtN систематически душит решение, и тем сильнее, чем больше dim. Несущий базис от
этого иммунен по построению (его строки выполняются тождественно), обычный — нет,
поэтому на этом стенде они несравнимы. **Второе следствие важнее первого:
подозреваемый №2 из M18 (43% столбцов без уравнений) повышен до ГЛАВНОГО, и
лечение у него то же самое — квадратная постановка.**
Побочно: **подозреваемый №1 (избыточность фрейма) ОСЛАБЛЕН** — направления не
балласт, а аппроксимационная сила; и **число «9000 итераций» из M18 завышено в
4–9 раз**: это итерации до МИНИМУМА, а до рабочей точности их 1000–4000.

## [1] ПОЧЕМУ ЭТАЛОН НЕ ПОЛУЧИЛСЯ (и это измерено, а не предположено)

Обычный базис (`carrier=0`, ND=1, всё остальное — тот же стенд, та же граница,
тот же эталон Ми), **вакуум, где точное решение — плоская волна и никакой
pollution нет**:

| W | dim | ошибка поля на r=2λ |
|---|---|---|
| λ/4 | 1 793 | 0.208 |
| λ/8 | 6 077 | 0.158 |
| λ/16 | 22 133 | **0.508** |

Квадратичный сплайн при λ/16 обязан воспроизводить плоскую волну с точностью
~1e-4. **Ошибка 0.5, РАСТУЩАЯ при измельчении, — это дефект постановки, и никакая
интерпретация про «pollution» его не покрывает.**

Механизм виден в счёте строк: операторные строки ОДНОРОДНЫ (правая часть ноль),
их ~dim, а несут привод только 91 строка DtN. `u = 0` удовлетворяет всем
однородным строкам ТОЧНО, поэтому минимизатор тем охотнее разменивает привод на
операторную невязку, чем больше однородных строк. Свип веса DtN на рассеивателе
(W=λ/8) подтверждает направление, но НЕ вылечивает:

| вес DtN | 1 | 10 | 100 | 1000 | 10⁴ |
|---|---|---|---|---|---|
| ошибка | 0.262 | 0.201 | 0.186 | 0.183 | 0.183 |
| \|u\| (точное 0.956) | 0.777 | 0.802 | 0.808 | 0.808 | 0.807 |

Вес выходит на плато, а поле остаётся коротким на 15%. Значит дефект не один, но
для вывода этого достаточно: **сравнивать два базиса на такой постановке нельзя,
один из них ею искалечен.**

**И это же объясняет, почему несущий базис так хорошо выглядел.** Его операторные
строки удовлетворяются ТОЖДЕСТВЕННО любой трефтцевой комбинацией — сжимать `u`
бессмысленно, выигрыша в невязке нет. То есть иммунитет несущего базиса к этому
дефекту реален и является его структурным преимуществом, но **он же маскировал
дефект три сессии подряд.**

## [2] ИЗБЫТОЧНОСТЬ ФРЕЙМА: ПОДОЗРЕВАЕМЫЙ №1 ОСЛАБЛЕН

Свип по ND при НЕПОДВИЖНОМ домене (R=5λ, W=λ/2, 64 фасета) — то самое различение
«избыточность против размера сцены»:

| ND | dim | ошибка поля | итераций до 2% |
|---|---|---|---|
| 2 | 1 364 | 0.532 | не достигнуто |
| 4 | 2 728 | 0.223 | не достигнуто |
| 8 | 5 456 | **0.0107** | **1 000** |
| 16 | 10 912 | **0.0034** | **1 000** |

Направления нельзя убрать: при ND=4 ответа просто нет. **Насыщения по ND тоже нет:
8 → 16 улучшает втрое (0.0107 → 0.0034), то есть закон `ND ≈ 3+20·W/λ = 13`
(F-II) на этой точке НЕ подтверждается — при W=λ/2 предсказанного насыщения около
13 направлений не наблюдается, ND=16 всё ещё покупает точность.** Итераций до 2%
при этом столько же (1000), то есть удвоение направлений не ухудшает сходимость —
цена только в nnz (1.59e6 → 5.92e6). Значит `16·ND = 128`
функций на точку — **не балласт, а аппроксимационная сила**, и версия M18
«избыточность фрейма и есть источник cond» в лоб не подтверждается. Что остаётся
проверяемым: не избыточны ли направления МЕЖДУ СОБОЙ при фиксированной
аппроксимации — это вопрос локальной ортогонализации (SVD по элементу), и он
теперь отдельный, а не главный.

## [3] ПОПРАВКА К M18, КОТОРУЮ НАДО СДЕЛАТЬ ЯВНО
M18 писал «9000 итераций» и строил на этом всю арифметику стоимости. Это итерации
до МИНИМУМА ошибки (0.88%). До рабочей точности: **1 000 итераций до 2%, 4 000 до
1%**. Стоимость в M18 завышена в 4–9 раз. Вывод M18 («константа аномальна, её надо
объяснять до экстраполяции») не меняется, но множитель был мой и неверный.

Заодно лучшая на сегодня точка гейта D2: R=5λ, ND=8, 64 фасета —
**поле 1.07%, диаграмма 1.66%**.

## [4] ЧТО ДЕЛАТЬ ДАЛЬШЕ — ОДИН ПУНКТ ВМЕСТО ШЕСТИ
Из шести пунктов плана M18 два слились в один и стали блокирующими:
**КВАДРАТНАЯ ПОСТАНОВКА** — столбцы до `R`, строки = столбцы, DtN замыкает
систему на `r = R`, а не проходит сквозь базис.

Она чинит сразу три вещи:
1. убирает 43% столбцов без уравнений (подозреваемый №2);
2. делает эталон стоимости ИЗМЕРИМЫМ (обычный базис перестаёт быть искалеченным);
3. делает систему квадратной ⇒ на этих размерах применим ПРЯМОЙ решатель, то есть
   вопрос «сколько итераций» на время проверки вообще снимается с дороги.

Пункты «локальная ортогонализация» и «агрегация тонких долек» остаются, но после.
