# M20: КВАДРАТНАЯ ПОСТАНОВКА — отчёт (2026-07-26)

## ВЫВОД
**Дефект найден и устранён, и он был именно там, куда указывал M19.** DtN,
переставленный из ОТДЕЛЬНЫХ СТРОК в ГРАНИЧНЫЙ ЧЛЕН уравнений, убирает все три
патологии сразу: столбцов без уравнений больше нет (было 43%), однородные строки
больше не переголосовывают привод, а система стала квадратной. **Обычный базис,
который старая постановка калечила, теперь работает — и знаменатель наконец
измерен.** Он оказался скромным: несущий базис выигрывает у обычного втрое по
точности при том же числе неизвестных, а не на порядки.

## [1] ЧТО ИЗМЕНИЛОСЬ В ФОРМУЛИРОВКЕ
Область Ω = {r<R}, все объёмные интегралы обрезаны на неё. Теорема Грина по Ω
даёт граничный член, на который и вешается условие излучения:
```
a(u,v) − ℓ(v) = −[Strong^Ω + Нитше] + ∮_{r=R} v (∂_r u − Λu − g)
```
То есть **`entry()` и член Нитше остались целиком** — добавились обрезка на Ω и
граничный блок. Правая часть `g_m = i^|m|(kJ'_|m| − Z_m J_|m|)` — та же величина,
что и раньше (гейт D2-1, 7.8e-15), но входит теперь в КАЖДУЮ приграничную строку,
а не в 91 отдельную.

**Граничный блок хранится РАЗЛОЖЕННЫМ, а не матрицей.** Он связывает каждую
приграничную функцию с каждой: при W=λ/2 и ND=8 это 2848² = 8.1·10⁶ элементов —
больше всего объёмного блока, и растёт как КВАДРАТ приграничного кольца. Как
оператор он ранга 2·mmax+1 = 91. Первая реализация развернула его в CSR и уткнулась
в лимит; переделано на факторизованное применение в матвеке.

Единственная неконсистентность названа и напечатана: объём режется
МНОГОУГОЛЬНИКОМ, а символ Λ диагонализуется на КРУГЕ. При 96 фасетах стрелка
1.87e-3 λ = 5.4e-4 от R — на порядок ниже целевой точности.

## [2] ПРОВЕРКА В ВАКУУМЕ (точное решение известно и представимо)

| базис | старая постановка | КВАДРАТНАЯ |
|---|---|---|
| несущий, ND=8, R=3.5λ | 4.1e-3 | **8.3e-4** |
| обычный, W=λ/4, R=5λ | 0.208 | **0.199** |
| обычный, W=λ/8, R=5λ | 0.158 | **0.0106** |
| обычный, W=λ/16, R=5λ | 0.508 (РОС) | — |

Обычный базис при λ/8 стал точнее в **15 раз**, и ошибка снова ПАДАЕТ при
измельчении (0.199 → 0.0106), то есть сходимость восстановлена. Именно этого
требовал диагноз M19.

Побочно: `|r|/|b| < 1e-4` теперь достигается (2139 итераций у несущего в вакууме),
а старая постановка до 1e-4 не доходила ВООБЩЕ ни в одном прогоне.

## [3] ЗНАМЕНАТЕЛЬ (то, ради чего всё затевалось)
Одна сцена, один домен, одна граница, одна постановка, один эталон.
Цилиндр n=1.5, a=1λ, R=5λ, 64 фасета, 12 000 итераций:

| базис | dim | nnz | поле r=2λ | диаграмма |
|---|---|---|---|---|
| обычный, W=λ/8 | 6 045 | 1.75e6 | 2.08% | 3.61% |
| **несущий, W=λ/2, ND=8** | **4 688** | 1.67e6 | **0.67%** | **1.08%** |

**Несущий базис выигрывает втрое по точности при 0.78 от числа неизвестных и
0.95 от nnz.** Это выигрыш, но СКРОМНЫЙ — и он ровно тот, который аудит среза
предсказал ещё до всех прогонов (§4 SLICE_PLAN: «при W ≤ λ/2 несущий базис НЕ
ДЕШЕВЛЕ сетки λ/8»). Теперь это измерено, а не выведено.

**Где выигрыш обязан быть большим и где он здесь не мерился:** при W ≫ λ. Срез
живёт при W=λ/2, то есть в режиме, где трефтцевого размена почти нет. Утверждение
архитектуры — про крупный элемент и УЗКОЕ угловое содержание; у рассеивателя оно
широкое. Этот стенд меряет худший для метода случай, и так и было записано заранее.

## [4] СОСТОЯНИЕ ГЕЙТА D2
Лучшие числа на предписанной конфигурации (R=5λ, r_m=2λ):
поле **0.67%**, диаграмма **1.08%** при пороге 5%; NC-D = 0.564, то есть
выигрыш у негативного контроля в 84 и 52 раза. Ошибка ещё падает с итерациями
(6.7e-3 на 12 000 против 8.8e-3 на 6 000), значит это ВЕРХНЯЯ оценка.

Не хватает для объявления гейта прежнего: сходимости по фасетам и плато LSQR на
этой конфигурации (кривая печатается, но дна ещё не достигла).

## [5] ЧТО ДАЛЬШЕ
1. Плато LSQR и сходимость по фасетам на квадратной постановке ⇒ гейт D2.
2. Старая постановка (`square=0`) остаётся только для регрессии; после гейта
   удаляется вместе с коллокационным путём — две формулировки в одном стенде
   долго держать нельзя.
3. Открыто с M18: разброс норм строк 1e9 (тонкие дольки разреза, подозреваемый
   №3) — не трогался и в этой постановке остаётся.
