# M9b: несущий базис на аналитической сборке — отчёт (2026-07-25)

Инструмент: `tools/carrier1d.c` (переписан), гейт ccheck CLEAN.
Сцена: 1024 ячейки = 64λ (λ=16 ячеек), источник на x=128, глобальное
поглощение α=0.02, рампы 32 ячейки по краям. Эталон — независимый FD/Томас.
Окна ошибки на 5/15/30/42λ от источника.

## Итог одной строкой
**КРАСНЫЙ ФЛАГ НЕ ПОДНЯТ.** Выигрыш по стоимости есть, но он СЛАБЕЕ выигрыша
по неизвестным. Главная находка не про стоимость: предел размера элемента
задаётся СТРУКТУРОЙ (источником), а НЕ переносом — в свободном распространении
элементы можно укрупнять как угодно.

## [1] A1 закрыт: аналитика == квадратура
`max |err_analytic − err_quad| = 2.0e-11` на общей конфигурации (порог был
1e-3). Квадратурная сборка оставлена в файле независимым свидетелем.
Механика: cos·cos = ½(1+cos2kx), sin·sin = ½(1−cos2kx), cos·sin = ½sin2kx ⇒
каждый элемент = комбинация ∫φ^(a)φ^(b)dx и ∫φ^(a)φ^(b)e^{i2kx}dx, обе в
замкнутой форме. **Число вызовов не зависит от k** — λ-сетка в сборку больше
не проникает.
Среда кусочно-постоянна ⇒ 1024 ячейки схлопываются в **65 сегментов**
постоянного Δk² (рампы + одна внутренность): член среды стоит O(рампы).

## [2] Четвёрка стоимости и ошибка от размера элемента
| конфигурация | dim | nnz/строку | вызовов | asm | rank | cond | err@5 | @15 | @30 | @42 |
|---|---|---|---|---|---|---|---|---|---|---|
| FINE λ/8 | 1034 | 13.9 | 92642 | 0.03 c | 1028/1034 | 2.4e5 | 0.003 | 0.006 | 0.015 | 0.022 |
| MIXED 1λ | 248 | 20.2 | 58532 | 0.01 c | 230/248 | 3.4e5 | 0.005 | 0.008 | 0.019 | 0.034 |
| MIXED 2λ | 184 | 22.0 | 52980 | 0.01 c | 170/184 | 4.0e5 | 0.039 | 0.066 | 0.144 | 0.283 |
| MIXED 4λ | 152 | 23.3 | 50212 | 0.01 c | 142/152 | 4.4e5 | 0.073 | 0.066 | 0.239 | 0.409 |
| MIXED 8λ | 136 | 24.4 | 48868 | 0.01 c | 126/136 | 4.5e5 | 0.248 | 0.133 | 0.523 | 1.921 |

Отношения к FINE: dim ×0.13–0.24, вызовы ×0.53–0.63, сборка ×0.33–0.38.

**СТОИМОСТЬ НЕ СЛЕДУЕТ ЗА НЕИЗВЕСТНЫМИ.** dim падает в 4–8 раз, а сборка —
только в 3. Причина видна в таблице: **nnz/строку РАСТЁТ при укрупнении**
(13.9 → 24.4). Это межуровневая связность: крупный элемент перекрывает много
мелких из зон уточнения. Плюс крупный элемент задевает больше сегментов среды.
Вход в вопрос 4 плана: матрица становится меньше, но плотнее по строкам.

**Столбец времени решения НЕНАДЁЖЕН и в таблицу не вынесен**: плотный zgelsd
даёт разброс от прогона к прогону на одном и том же входе (FINE: 21.5 c и
32.8 c; SEAM 1→2: 0.02 c и 3.21 c). Ошибки при этом воспроизводятся бит-в-бит.
Прод-путь всё равно не плотный — значимые метрики стоимости здесь dim, nnz,
вызовы, сборка.

## [3] ГЛАВНАЯ НАХОДКА: предел задаёт структура, а не перенос
Шов между размерами элементов посреди свободного распространения (x=512),
ближняя зона остаётся 1λ, дальняя укрупняется:

| дальняя зона | dim | err@30 | err@42 |
|---|---|---|---|
| 1λ везде (бесшовно) | 248 | 0.019 | 0.034 |
| 2λ | 216 | 0.019 | 0.029 |
| 4λ | 200 | 0.014 | 0.033 |
| 8λ | 192 | 0.018 | 0.035 |
| **16λ** | **188** | 0.018 | **0.017** |

Ошибка **плоская** по всему диапазону: от 1λ до 16λ — то есть при укрупнении
дальних элементов в 16 раз (и в 128 раз относительно λ/8) точность не
деградирует. Разброс 0.017–0.035 — это шум порядка самой величины, тренда нет.
NB: не читать «16λ лучше всех» — единичное число, вероятно совпадение фаз.

Сравнить с РАВНОМЕРНЫМ укрупнением до 2λ: 0.283, то есть в 10 раз хуже.
Разница между этими двумя строками — только размер элементов У ИСТОЧНИКА.

**Теоретическое объяснение (проверяемое):** плоская волна cos(kx+ψ) лежит в
пролёте несущего базиса ТОЧНО, с постоянными коэффициентами — по разбиению
единицы Σφ(x/W−n) = 4, при ЛЮБОМ W. То есть свободное распространение
представляется без ошибки независимо от размера элемента, и «дисперсии
огибающей» в пустоте просто нет. Ошибка рождается там, где поле не является
плоской волной: у источника, у рамп, у геометрии — и дальше переносится.

**Следствие для архитектуры:** это ровно те «три регулятора» из PLAN.md —
LOD-потолок в свободном пространстве, контрастный пол у структуры. Данные их
подтверждают, а не иллюстрируют.

**Лучшая конфигурация прогона:** мелко у источника + 16λ в дальней зоне —
dim 188 против 1034 (×0.18) при ошибке 0.017 против 0.022. **Меньше
неизвестных в 5.5 раза при не худшей точности.**

## Вход в открытые вопросы плана
- **Вопрос 3 (диадические оболочки):** стоимость перехода между размерами
  элементов — В ПРЕДЕЛАХ ШУМА. Шов посреди свободного распространения не
  портит поле ниже по трассе. Гипотеза диадических оболочек не встречает
  здесь препятствия.
- **Вопрос 4 (решатель):** nnz/строку 14–25; матрица меньше, но плотнее.
  Обусловленность 2.4e5 → 4.8e5 на диапазоне размеров элемента 128× — то есть
  **классическая болезнь Трефтца НЕ взрывается**. Это снимает главное
  теоретическое возражение против переполненного базиса, но проверено только
  в 1D с одной несущей.
- **Вырожденность:** нулевых мод 6/1034 (FINE) против 18/248 (смешанные
  уровни) — межуровневая избыточность, как и заложено; min-norm справляется.

## [4] МАСШТАБНОЕ ИССЛЕДОВАНИЕ (tools/carrier_scale.c) — 10³..10⁸ λ
Замечание юзера: 16λ — не тот масштаб, нужны 10³ и 10⁷. Стенд под это пришлось
переделать: FD-эталон требует ~128 точек на λ и дальше пары сотен λ не тянет.
Заменён на **аналитическую функцию Грина** однородной среды (верна на любом
расстоянии, сетки нет — принцип A4 аудита), среда — **список сегментов**, а не
массив ячеек, поэтому ни сцена, ни сборка не растут вместе с доменом.
Общая математика вынесена в `src/carrier.{c,h}` (понадобится в M9c).

### Стоимость масштабируется как обещано
Домен 640 → 6.4e8 λ (шесть порядков), LOD-лестница `L = ε·R`:
размерность 362 → 992, уровней 7 → 27, вызовов 7.2e4 → 2.8e5, элементы до
**8.4·10⁶ λ**. Рост логарифмический. Это подтверждено.

### Точность — НЕ подтверждена
| домен, λ | уровней | Wmax/λ | dim | cond | err@25/50/75% |
|---|---|---|---|---|---|
| 640 | 7 | 8 | 362 | 1.2e6 | 0.055 / 0.025 / 0.035 |
| 6.4e4 | 13 | 512 | 642 | 3.1e8 | 0.62 / 0.63 / 0.63 |
| 6.4e6 | 20 | 65536 | 810 | 6.6e9 | 0.55 / 0.39 / 0.24 |
| 6.4e8 | 27 | 8.4e6 | 992 | 9.7e9 | 0.25 / 0.33 / 0.43 |
На 640λ — 2–5%, как в [2]. Дальше деградация, строго коррелирующая с
обусловленностью: **cond растёт экспоненциально с глубиной лестницы**, ~0.2
порядка на уровень (7 уровней = 1e6, 27 уровней = 1e10).

### Два дефекта СТЕНДА, найденных по дороге (оба поучительны)
1. **Полоса уровня уже носителя.** Полосы `[W/(2ε), W/ε)` имеют ширину
   `W/(2ε)`, носитель φ равен `4W`. При ε=1/4 полоса вдвое уже носителя, запас
   на разбиение единицы обнуляет нижнюю границу, и ВСЕ уровни оказываются
   активны от самой структуры. Отсюда **ограничение на правило LOD: ε ≤ 1/8**,
   то есть размер элемента не может расти с расстоянием быстрее, чем позволяет
   ширина носителя. Это не тюнинг, это связь базиса с LOD.
2. **Поглотитель съедал источник.** Слой толщиной RAMPEL элементов при
   неограниченной лестнице (верхний элемент — заметная доля домена) занимал
   четверть мира, и источник на 0.15·dom оказывался ВНУТРИ него: поле гибло при
   рождении, err = 1.0. Лечится ограничением на крупнейший элемент
   (WMAX_FRAC = 1/64). Артефакт стенда, не свойство базиса — но именно он
   маскировал реальную картину два прогона подряд.

### [4b] Свип по RCOND: усечение или вырождение? — ВЫРОЖДЕНИЕ
| домен | лучший rcond | err там | при RCOND=1e-10 |
|---|---|---|---|
| 6.4e4 λ | 1e-6 | 0.08 / 0.10 / 0.14 | 0.49 / 0.51 / 0.52 |
| 6.4e6 λ | 1e-8 | 0.21 / 0.28 / 0.44 | 0.60 / 0.48 / 0.48 |
| 6.4e8 λ | 1e-10 | 0.31 / 0.36 / 0.48 | — |
- **smin/smax = 1.5e-17 … 2.3e-17 ВО ВСЕХ случаях**: сингулярные числа доходят
  до машинного эпсилон. Базис вырожден численно до предела двойной точности —
  это не неудачный порог, малые моды это шум.
- Порог при этом решает МНОГО: 0.49 → 0.08 на 6.4e4 λ, то есть в 6 раз.
  Значит принятый в проекте фиксированный `RCOND = 1e-10` для этого базиса
  просто неверен, а оптимум ползёт с размером задачи.
- Но даже в оптимуме точность падает с глубиной: 8% → 21% → 31%.

### ГЛАВНЫЙ ВЫВОД [4] и что делать
Лестница, решаемая ОДНОЙ монолитной системой, вырождена по построению и на
масштабе не работает. Но именно так делать план и не велел: в «Решениях по
линейной алгебре» записано «предобуславливатель не нужен: **межуровневую
избыточность снимает КАСКАД**». В этом стенде каскада нет — все 27 уровней
брошены в один плотный zgelsd. То есть измерена цена ОТКАЗА от каскада, а не
предел метода.
Следующий шаг — не тюнинг rcond, а каскадное решение коарс-ту-файн в этом же
стенде. Это одновременно первое настоящее упражнение по вопросу 3 плана
(диадические оболочки) и по вопросу 4 (архитектура решателя).

## [5] ПРОЕКЦИОННЫЙ ТЕСТ (tools/carrier_proj.c) — представимость без решателя
Поставлен после аудита самого эксперимента: четыре стенда подряд ломались на
границе домена или на лестнице, и каждый раз я отчитывался до того, как стенд
становился надёжным. Здесь этих движущихся частей нет вовсе — проецируем
ИЗВЕСТНОЕ точное поле на базис и меряем остаток. Это НИЖНЯЯ ГРАНИЦА для любого
галёркинского решения: провал здесь — приговор, успех здесь ничего не обещает
про решение (Гельмгольц знаконеопределён, квазиоптимальность не даётся даром).
Правки по аудиту: один уровень за раз (A1), окно ПОВЕРХ структуры (A2),
несущая локальна по среде (A3), всё в замкнутой форме (B3), сэмплированный
свидетель (B4). Предпосылка — новая примитива `hz_phi_integral_osc`
(один φ-множитель × e^{iωx}), 980/980 в test_phi.

Относительная L2-ошибка наилучшего приближения, окно ±2 элемента вокруг
структуры:

| поле | W=λ/8 | λ | 10λ | 10²λ | 10³λ | 10⁵λ |
|---|---|---|---|---|---|---|
| **F1** плоская волна, несущая совпадает | 0 | 0 | 2e-8 | 0 | 2e-8 | **0** |
| **F2** плоская волна, несущая НЕ совпадает | 1.6e-4 | 0.636 | 0.9998 | 1.000 | 1.000 | 1.000 |
| **F3** излом точечного источника e^{ik\|x\|} | 0.0163 | 0.162 | 0.193 | 0.193 | 0.193 | 0.193 |
| **F4** граница среды, ОДНА глобальная несущая | 4.2e-3 | 0.421 | 0.719 | 0.720 | 0.720 | 0.720 |
| **F5** граница среды, несущая ЛОКАЛЬНА | 3.4e-3 | **0.040** | 0.203 | 0.206 | 0.206 | 0.206 |

Свидетель (B4): аналитика против сэмплирования совпадают до 1e-9, для F1 —
1.8e-15. Общего бага нет.

### Три вывода, и первый закрывает главный вопрос архитектуры
1. **F1: свободное распространение представимо ТОЧНО при любой ширине** —
   ноль ошибки вплоть до 10⁵λ. Основное утверждение всей конструкции доказано
   независимо от решателя, границы и обусловленности. Раньше это было теорией
   плюс косвенными данными; теперь измерено прямо.
2. **F2: НЕСУЩАЯ ОБЯЗАНА БЫТЬ ЛОКАЛЬНОЙ ПО СРЕДЕ.** Плоская волна с k'=1.5k,
   изображаемая несущей с k, даёт 100% ошибки при W≥10λ — БЕЗ всякой
   сингулярности, на гладчайшем поле. Одна глобальная несущая означает, что
   каждая граница материала требует элементов λ/8. F5 против F4: на W=λ ошибка
   падает 0.42 → 0.040, в 10 раз. Это жёсткое архитектурное требование, и в
   спеке его не было.
3. **Разрыв (сингулярность) даёт ПОЛ ~20%, не зависящий от ширины.** F3 и F5
   выходят на 19–21% и там стоят. Причём ошибка НЕ убывает как 1/√W, хотя
   дефект точечный — значит невязка размазана по ВСЕМУ носителю элемента.
   Механизм: элемент, накрывающий разрыв, должен одной гладкой огибающей
   изобразить «волна влево» слева и «волна вправо» справа, и портится целиком.
   ⇒ ВТОРОЕ требование: **элементы не должны пересекать разрывы среды.** Для
   октодерева это естественно (границы материалов и есть границы узлов), но
   как требование к базису нигде не записано. Прямо НЕ измерено — следует из
   механизма; проверяется отдельно.

### Ответ на исходный вопрос «есть ли пол λ у структуры»
Есть, но он **локален и двухсоставен**: у гладкой границы он снимается
локальной несущей (F5 на W=λ: 4%), а остаток ~20% — это сам разрыв, и он
лечится не измельчением, а тем, что элемент не должен на разрыв садиться.
Настоящее сверх-λ измельчение нужно только там, где поле действительно
сингулярно, и стоит оно 1.6% на λ/8 против 19% на крупных.

## [6] ЗАКОН ТОЧНОСТИ ФАЗЫ (вопрос 13) — ПОДТВЕРЖДЁН С КОНСТАНТОЙ
Поле — плоская волна с `k' = k(1+δ)`, несущая с `k`; бинарный поиск по W до
порога 10% ошибки проекции.

| δk/k | W_max/λ | **W_max·δ/λ** |
|---|---|---|
| 5e-1 | 0.642 | 0.3211 |
| 1e-1 | 3.14 | 0.3143 |
| 1e-2 | 31.4 | 0.3142 |
| 1e-3 | 314 | 0.3142 |
| 1e-4 | 3142 | 0.3142 |
| 1e-5 | 3.14e4 | 0.3142 |

Последняя колонка **постоянна на пяти порядках** и равна `1/π`:
```
W_max = λ / (π · δk/k)
```
Эквивалентно: набег фазы поперёк ОДНОЙ ширины элемента должен оставаться
≲ 2 рад на пороге 10%. Отклонение при δ=0.5 (0.3211) — ожидаемый выход
асимптотики из применимости при δ ~ 1.

**Что это даёт как проектное число** — «насколько точно надо знать среду»:
элементы 10³λ требуют `δk/k ≲ 3e-4`, элементы 10⁶λ — `3e-7`. Через
`δx ≲ 1/(k₂−k₁)` то же ограничение переводится в допуск на положение границы.
Это входной параметр для градиентных сред (вопрос: как точно нужен ВКБ-эйконал)
и для формата сцены.

## [7] РАЗРЕЗ ПРОТИВ ГЛАДКОГО ЭЛЕМЕНТА (вопрос 10) — ПОДТВЕРЖДЁН

| W/λ | ошибка гладкого | **ошибка разрезанного** | dim гладк/разрез | скачок/\|u\| |
|---|---|---|---|---|
| 0.125 | 3.4e-3 | 0 | 30/60 | 1.2e-12 |
| 1 | 4.0e-2 | 0 | 30/60 | 5.4e-15 |
| 10 | 0.203 | 3.0e-8 | 30/60 | 1.2e-14 |
| 10² | 0.206 | 0 | 30/60 | 6.6e-15 |
| 10³ | 0.206 | 0 | 30/60 | 3.4e-15 |
| 10⁴ | 0.206 | 0 | 30/60 | 1.4e-14 |
| 10⁵ | 0.206 | **0** | 30/60 | 3.5e-15 |

**Разрез чинит представимость полностью и при любой ширине.** Гладкий элемент
упирается в 20% (невязка размазана по всему носителю), разрезанный даёт
МАШИННЫЙ НОЛЬ вплоть до 10⁵λ. Цена — удвоение степеней свободы, и только на
элементах, которых граница касается: одна степень на пару (элемент × сторона).
Это переводит утверждение из «вывод по механизму» в измерение.

**ЧЕГО ЭТОТ ЗАМЕР НЕ РЕШАЕТ — конформность (вопрос 10, вторая половина).**
Скачок вышел машинным нулём, но это НЕ доказывает конформность: в этом тесте
каждая сторона представима ТОЧНО, проекция совпадает с полем, а раз v ≡ u, то
непрерывность наследуется от самого поля — конформности просто не на чем
отказать. Проверять надо на поле, которое на сторонах представимо лишь
ПРИБЛИЖЁННО (например с изломом точечного источника на одной из сторон); тогда
независимые проекции сторон могут разойтись на границе. Вопрос остаётся
открытым, замер его не закрыл.

**ПОЙМАННЫЙ АРТЕФАКТ ИЗМЕРЕНИЯ.** Первая версия колонки скачка вычисляла его в
точках `xsplit ± 1e-6·W`, то есть со смещением, РАСТУЩИМ вместе с элементом.
Она мерила разрыв производной, помноженный на это смещение, и давала рост
1.6e-6 → 1.41 линейно по W — то есть «катастрофическую неконформность на
крупных элементах», которой нет. Исправлено на односторонние суммы ровно в
`xsplit` (обе стороны там определены, epsilon не нужен).

## Ограничение (существенное)
1D. Направлений всего два, и пара cos/sin покрывает оба — то есть **угловая
разреженность здесь вырождена и не проверяется вообще**. Всё, что показано, —
необходимое, но не достаточное условие. Настоящая проверка — M9c (2D, набор
кандидатных несущих, доля выживших).

## [8] КОНФОРМНОСТЬ РАЗРЕЗА (вопрос 10, вторая половина) — ИЗМЕРЕНА
§7 показал, что разрез чинит представимость, но конформность там проверить было
нельзя: каждая сторона была представима ТОЧНО, значит `v ≡ u` и непрерывность
наследовалась от поля, а не производилась базисом. Здесь правая сторона
представима лишь ПРИБЛИЖЁННО (поле разворачивает направление в 40λ за разрезом,
чего одна несущая не держит), поэтому у двух независимых односторонних проекций
нет причин совпасть на границе.

| W/λ | ошибка разрезанного | **скачок/\|u\|** |
|---|---|---|
| 0.125 | 0 | 1.2e-12 |
| 1 | 0 | 5.4e-15 |
| 10 | 3.0e-8 | 1.2e-14 |
| 100 | 0.167 | **3.4e-3** |
| 1000 | 0.123 | **9.8e-5** |

**Скачок появляется РОВНО тогда, когда стороны перестают быть представимыми, и
даже тогда он на два-три порядка меньше самой ошибки приближения** (0.03–0.3%
против 12–17%). Пока элемент справляется с полем на своей стороне —
непрерывность выходит машинной сама собой, без каких-либо связей.

ОГОВОРКА, без которой вывод был бы завышен: L2-проекция скачок НЕ ШТРАФУЕТ
вообще, то есть это худший случай — ничто не мешало ей разойтись сильнее. В
галёркинской постановке скачок войдёт в невязку через производные и может
значить больше. Так что измерено: неконформность мала как ВЕЛИЧИНА; её влияние
на решение — отдельный вопрос, и он требует оператора.
